services:

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - auth
      - user
      - captain
      - ride
      - payment
      - call-service
    networks:
      - backend

  auth:
    build: ./auth
    container_name: auth
    ports:
      - "3004:3004"
    env_file:
      - /home/ubuntu/config/auth-service.env
    depends_on:
      - redis
    networks:
      - backend

  user:
    build: ./user
    container_name: user
    ports:
      - "3001:3001"
    env_file:
      - /home/ubuntu/config/user-service.env
    depends_on:
      - redis
    networks:
      - backend

  captain:
    build: ./captain
    container_name: captain
    ports:
      - "3002:3002"
    env_file:
      - /home/ubuntu/config/captain-service.env
    depends_on:
      - redis
    networks:
      - backend

  ride:
    build: ./ride
    container_name: ride
    ports:
      - "3003:3003"
    env_file:
      - /home/ubuntu/config/ride-service.env
    depends_on:
      - redis
    networks:
      - backend

  payment:
    build: ./payment
    container_name: payment
    ports:
      - "3006:3006"
    env_file:
      - /home/ubuntu/config/payment-service.env
    depends_on:
      - redis
    networks:
      - backend
  call-service:
    build: ./call-service
    container_name: call-service
    ports:
      - "3005:3005"
    env_file:
      - /home/ubuntu/config/call-service.env
    depends_on:
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge