services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  gateway:
    image: surajbalal/gateway:${GATEWAY_VERSION}
    container_name: gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - auth
      - user
      - captain
      - ride
      - payment
      - call-service
    networks:
      - backend

  auth:
    image: surajbalal/auth:${AUTH_VERSION}
    container_name: auth
    ports:
      - "3004:3004"
    env_file:
      - ./auth-service.env
    depends_on:
      - redis
    networks:
      - backend

  user:
    image: surajbalal/user:${USER_VERSION}
    container_name: user
    ports:
      - "3001:3001"
    env_file:
      - ./user-service.env
    depends_on:
      - redis
    networks:
      - backend

  captain:
    image: surajbalal/captain:${CAPTAIN_VERSION}
    container_name: captain
    ports:
      - "3002:3002"
    env_file:
      - ./captain-service.env
    depends_on:
      - redis
    networks:
      - backend

  ride:
    image: surajbalal/ride:${RIDE_VERSION}
    container_name: ride
    ports:
      - "3003:3003"
    env_file:
      - ./ride-service.env
    depends_on:
      - redis
    networks:
      - backend

  payment:
    image: surajbalal/payment:${PAYMENT_VERSION}
    container_name: payment
    ports:
      - "3006:3006"
    env_file:
      - ./payment-service.env
    depends_on:
      - redis
    networks:
      - backend
  call-service:
    image: surajbalal/call-service:${CALL_SERVICE_VERSION}
    container_name: call-service
    ports:
      - "3005:3005"
    env_file:
      - ./call-service.env
    depends_on:
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge
